version: '3.8'

services:
  web:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - ~/.kube:/root/.kube:ro  # Mount kubeconfig directory as read-only
      - .env:/app/.env
    environment:
      - FLASK_ENV=production
    restart: unless-stopped 